### PR TITLE
implemented removeArtist in MusicData, added more MusicData tests, fixed some import errors

### PR DESCRIPTION
**Pull request by dallasschn**
- implemented removeArtist in MusicData
- Added more tests for MusicData
- fixed some import errors
- updated frontend to use MusicDataBuilder

### CODE REVIEW

**Review by jmlee3210 — DISMISSED** [review]
great!!

**Review by yuyangggggg — APPROVED** [review]

**Review by jmlee3210 — APPROVED** [review]
awesome

**Review by yuyangggggg — DISMISSED** [review]

**Review by maxXu0713 — DISMISSED** [review]
Great addition to MusicDataTest, but there are some CA violations in non-test files. Frontend makes use of the CA violation, but both LoginFrame and RegisteredUser break CA seemingly without any changes that require the CA violation. (CA doesn't matter for the MusicDataTest)

**Review by jmlee3210 — APPROVED** [review]
great

**Pull request merged**
