### PR TITLE
MusicData tests and static method updates

### PR DESCRIPTION
**Pull request by dallasschn**
Added tests for MusicData to test the hashmap "data" and the methods that interact with it. Also made a few methods in MusicData static because they need to be in order for the class to work properly.

### CODE REVIEW

**Review by jmlee3210 — APPROVED** [review]
lgtm

**Review by jmlee3210 — DISMISSED** [review]

**Review by SahirD — CHANGES_REQUESTED** [review]
All the test cases are good. The one you commented out for getTop isn't working because the artists you wrote aren't the top ones in our database. Top Spotify streams in the database is Drake, followed by Bad Bunny

**Review by jmlee3210 — APPROVED** [review]
lgtm

**Review by maxXu0713 — APPROVED** [review]
looks good, makes necessary functions static and implements tests

**Review by dallasschn — COMMENTED** [review]
changes added

**Pull request merged**
