### PR TITLE
Added method signatures to rest

### PR DESCRIPTION
**Pull request by michaelzixizhou**

### CODE REVIEW

**Review by maxXu0713 — COMMENTED** [review]
very good

**Review by jmlee3210 — APPROVED** [review]
Very good

**Review by maxXu0713 — APPROVED** [review]
very good

**Review by yuyangggggg — APPROVED** [review]
great work

**Comment by tanmah2809** [comment]
https://stackoverflow.com/questions/22493765/java-do-nothing
https://www.rose-hulman.edu/class/cs/csse220/200820/web/Resources/Python_vs_Java.html

**Pull request merged**
